#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

[ -f "$SB_DATA/config.ini" ] ||\
  dockerize \
    -template /templates/config.ini.tpl:$SB_DATA/config.ini \
    echo "==> Writing $SB_DATA/config.ini from /templates/config.ini.tpl"

echo "==> Starting dnsmasq, I hope you gave me NET_ADMIN"
dnsmasq --all-servers --local-service

mkdir -p $SB_DATA/{TV-Shows,Downloading,Torrents}

cd $SB_HOME
git checkout $SICKRAGE_CHANNEL
git pull --verbose

. /venv/bin/activate
export PYTHONPATH=$SB_HOME
exec -a "supervisord" "supervisord" "-c" "/etc/supervisord.conf"
exit 0
